; Flow32 — ESP32-S3 UI + SPI TFT (ST7789 / ST7735)
[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_mode = qio
board_build.flash_size = 8MB
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 8MB
board_build.embed_files =
  data/alexis.gif
build_flags =
  -DBOARD_HAS_PSRAM
lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit ST7735 and ST7789 Library
  adafruit/Adafruit BusIO
  bitbank2/AnimatedGIF
monitor_filters = direct
monitor_eol = LF
upload_port = /dev/cu.usbmodem5C390027041
monitor_port = /dev/cu.usbmodem5C390027041
